In [1]:
import numpy as np

In [2]:
# myarr = np.array([3,4,8,23,2] ,np.int8)
# myarr = np.array([3,4,8,23,2], np.int64)
# myarr = np.array([3,4,8,23,2] ,np.int32) 1 d array

myarr = np.array([[32, 14, 11, 88, 25]]) #2d array


In [3]:
myarr

array([[32, 14, 11, 88, 25]])

In [4]:
# myarr.dtype # by default 32 bit
myarr[0,2]

11

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr[0]

array([32, 14, 11, 88, 25])

In [7]:
myarr[0,3]=45

In [8]:
myarr

array([[32, 14, 11, 45, 25]])

In [9]:
myarr.size

5

# Array creation: Convertion from other python structures

In [10]:
listarr= np.array([[1,2,3], [4,5,6], [7,8,9]])

In [11]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarr[0,1]

2

In [13]:
listarr[2]

array([7, 8, 9])

In [14]:
listarr.shape

(3, 3)

In [15]:
listarr.dtype

dtype('int32')

# intrinsic numpy array creation objects

In [16]:
zer = np.zeros((2,4))

In [17]:
zer

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
zer.dtype

dtype('float64')

In [19]:
zer.shape

(2, 4)

In [20]:
rng = np.arange(18) # o to n-1 array

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [22]:
rng.shape

(18,)

In [23]:
rng.dtype

dtype('int32')

In [24]:
lspace= np.linspace(1,5,6) # equally Linearly space

In [25]:
lspace

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [26]:
lspace.dtype

dtype('float64')

In [27]:
emp = np.empty((2,6))

In [28]:
emp  # all elements are random

array([[2.75966138e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000, 1.18831764e-312, 1.36367727e+161],
       [1.91893371e-052, 5.15532618e-062, 7.24777008e+169,
        1.40505770e+165, 3.15686709e-033, 4.42607034e-062]])

In [29]:
emp.shape

(2, 6)

In [30]:
emp_like = np.empty_like(lspace)

In [31]:
emp_like

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [32]:
idn = np. identity(8)

In [33]:
idn # identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
idn.shape

(8, 8)

In [35]:
arr = np.arange(50)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [37]:
arr=arr.reshape(5,10)

In [38]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
arr= arr.ravel()

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
arr.shape

(50,)

In [42]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [43]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [44]:
ar = np.array(x)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.sum(axis = 0)

array([12, 15, 18])

In [47]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [48]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ar.flat

In [51]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [52]:
ar.ndim  # no. of dimensions ie, 2D

2

In [53]:
ar.nbytes  

#no. of bytes ie, 3(data)=32 bit (4 byte) total elements 3X3 = 9 *4 =36 bytes


36

In [54]:
m = np.array([10,5 ,11 ,55 ,2])

In [55]:
m

array([10,  5, 11, 55,  2])

In [56]:
m.argmax()  # it returns the index of maximum element

3

In [57]:
m.argmin()

4

In [58]:
m.argsort()  # it tells the indexes in the form of asending order

array([4, 1, 0, 2, 3], dtype=int64)

In [59]:
m.dtype

dtype('int32')

In [60]:
m

array([10,  5, 11, 55,  2])

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
ar.argmin()

0

In [63]:
ar.argmax(axis=0) # it returns indexes of max element in row

array([2, 2, 2], dtype=int64)

In [64]:
ar.argmax(axis=1) # it returns indexes of max element in col

array([2, 2, 2], dtype=int64)

In [65]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
ar2 = np.array([[4,8,7],[0,2,1],[8,2,5]])

In [69]:
ar2

array([[4, 8, 7],
       [0, 2, 1],
       [8, 2, 5]])

In [70]:
ar +ar2 # addition of two matrices

array([[ 5, 10, 10],
       [ 4,  7,  7],
       [15, 10, 14]])

In [71]:
ar * ar2

array([[ 4, 16, 21],
       [ 0, 10,  6],
       [56, 16, 45]])

In [72]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [73]:
ar.sum()

45

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
np.where(ar>7)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [76]:
np.count_nonzero(ar)

9

In [77]:
np.nonzero(ar)  # 0,0 = Non zero Value

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [78]:
ar[1,2]=0

In [79]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [80]:
import sys

In [81]:
py_ar=[1, 3, 4, 2]

In [82]:
np_ar=np.array(py_ar, np.int32)

In [83]:
sys.getsizeof(1) * len(py_ar)  # 28 *4 =112

112

In [84]:
np_ar.dtype

dtype('int32')

In [85]:
np_ar.itemsize

4

In [86]:
np_ar.itemsize * np_ar.size

16

In [87]:
np_ar.tolist()

[1, 3, 4, 2]

In [88]:
np_ar

array([1, 3, 4, 2])

In [89]:
y = np.arange(6).reshape(2,3)

In [90]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
print(np.argwhere(y))

[[0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]]


In [92]:
import pandas as pd

In [93]:
d = {'one': pd.Series([1,2], index = ['a','b']),
    'two': pd.Series([1,2,3], index =['a','b', 'c'])
    }

In [94]:
df = pd.DataFrame(d)

In [95]:
df

one  two
a  1.0    1
b  2.0    2
c  NaN    3

In [96]:
df['two'] = pd.Series([10,20], index =['a','b'])

In [97]:
df['three'] = df['one']+df['two']

In [98]:
print(df)

   one   two  three
a  1.0  10.0   11.0
b  2.0  20.0   22.0
c  NaN   NaN    NaN


In [99]:
z=np.array([12,24,45,0]);

In [100]:
z

array([12, 24, 45,  0])

In [101]:
data = np.array(['a','b'])

In [102]:
s = pd.Series(data)

In [103]:
s

0    a
1    b
dtype: object